### ISSUE TITLE
path shape

### ISSUE THREAD

**Issue by schweinebauch** [vampcoder/Artificial-Potential-Field#1]
hello, thanks for great job!I have a question about the trajectory generated in potential field method. Previously I also studied potential field path planning and got smooth trajectory in MATLAB(simulation), but when I burned my c++ code in a tow wheeled car the generated trajectory had much more oscillation(not smooth), how can I solve this problem? It is caused due to the wheel microcontroller or should I attach smooth strategy?

**Comment by vampcoder** [comment]
Hello, for actual environments you can use smooth trajectories using:
1) Smooth path using available spline methods.
2) Your controller function. The controller shouldn't take steep turn on next move/point provided. I solved it using v(omega) controller which keeps the V constant and vary omega based on the next point.
